/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.user_interface.fundacaqueta.Interfaces.Proyecto;

//Imports from logic
import com.logic.fundacaqueta.Fundacaqueta;

//Imports from java
import javax.swing.JOptionPane;

//Interface imports
import com.user_interface.fundacaqueta.InterfazAdmin;

/**
 *
 * @author nebel
 */
public class EliminarProyecto extends javax.swing.JFrame {

    private Fundacaqueta fundacaqueta;
    
    private InterfazAdmin parentAdmin;
    /**
     * Creates new form AgregarProyecto
     */
    public EliminarProyecto(Fundacaqueta fundacaqueta, InterfazAdmin parent) {
        initComponents();
        this.fundacaqueta = fundacaqueta;
        this.parentAdmin = parent;
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        bttnConfirmar = new javax.swing.JButton();
        bttnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Eliminar Proyecto");

        jLabel2.setText("Id (Posicion en la lista): ");

        bttnConfirmar.setText("Confirmar");
        bttnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnConfirmarActionPerformed(evt);
            }
        });

        bttnCancelar.setText("Cancelar");
        bttnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtId)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(bttnConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bttnCancelar)
                        .addGap(85, 85, 85))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnConfirmar)
                    .addComponent(bttnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bttnCancelarActionPerformed

    private void bttnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnConfirmarActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtId.getText());
        id--;
        if(revisarId(id)){
            if(confirmarOperacion(id)){
                fundacaqueta.obtenerProyectos().remove(id);
                JOptionPane.showMessageDialog(this, "Proyecto eliminado con éxito", "Exito", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                parentAdmin.updateProjects();
            }
        }
    }//GEN-LAST:event_bttnConfirmarActionPerformed

    private boolean revisarId(int id){
        if(id<0){
            JOptionPane.showMessageDialog(this, "El id no puede ser negativo o cero", "Id invalido", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else if(id > fundacaqueta.obtenerProyectos().size()-1){
            JOptionPane.showMessageDialog(this, "El id no existe", "Id invalido", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    private boolean confirmarOperacion(int id){
        boolean confirmar = false;
        
        String nombre = fundacaqueta.obtenerProyectos().get(id).obtenerNombre();
        String lugarEjecucion = fundacaqueta.obtenerProyectos().get(id).obtenerLugarEjecucion();
        String tipo = fundacaqueta.obtenerProyectos().get(id).obtenerTipo();
        String dialogo = "¿Está seguro que desea eliminar este proyecto?\n" 
                +"Nombre: " + nombre + "\n" 
                +"Lugar ejecucion: " + lugarEjecucion + "\n"
                +"Tipo: " + tipo + "\n";
        int respuesta = JOptionPane.showConfirmDialog(this, dialogo, "Confirmar", JOptionPane.YES_NO_OPTION);
        
        if(respuesta==JOptionPane.YES_OPTION)
            confirmar = true;
        
        return confirmar;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnCancelar;
    private javax.swing.JButton bttnConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
